---
- hosts: deploy
  tasks:
    - name: dots files
      git:
        repo: ssh://git@github.com/cympfh/dots.git
        dest: $HOME/.dots
        accept_hostkey: yes
  roles:
    - bin
    - pyenv
    - screen
    - vim
    - zsh
